### ISSUE TITLE
Remove DynamoDB streaming support

### ISSUE THREAD

**Issue by barryoneill** [laserdisc-io/fs2-aws#1016]
In short, the current DynamoDB streaming support in this project is based on the V1 SDK.  Unless a replacement is written, the existence of this support making upgrading dependencies in this project difficult. 

In particular, the function [parseDynamoRecord](https://github.com/laserdisc-io/fs2-aws/blob/main/fs2-aws-dynamodb/src/main/scala-3.0-/fs2/aws/dynamodb/parsers/package.scala#L40) exists to support parsing the records produced by [DynamoDB](https://github.com/laserdisc-io/fs2-aws/blob/main/fs2-aws-dynamodb/src/main/scala/fs2/aws/dynamodb/DynamoDB.scala#L32).  

## Problem

* this client is based on the AWS SDK v1 library
* `parseDynamoRecord` function accepts a payload which contains `com.amazonaws.services.dynamodbv2.model.AttributeValue` attributes (sdk V1)
* it then uses Scanamo's `DynamoObject` code to map these to Json 
* Scanamo (via scanamo-circe) cannot be upgraded, as it is now using SDK v2 classes (`software.amazon.awssdk.services.dynamodb.model.AttributeValue`)

## Proposal 1
We shouldn't be bringing in scanamo or scanamo-circe into fs2-aws in the first place, so I propose that [parseDynamoRecord](https://github.com/laserdisc-io/fs2-aws/blob/main/fs2-aws-dynamodb/src/main/scala-3.0-/fs2/aws/dynamodb/parsers/package.scala#L40) and the example that references it be dropped. 

## Proposal 2
All code relating to event streaming in [DynamoDB](https://github.com/laserdisc-io/fs2-aws/blob/main/fs2-aws-dynamodb/src/main/scala/fs2/aws/dynamodb/DynamoDB.scala#L32) should be dropped so that `com.amazonaws` (v1 SDK) is no longer a dependency of this project. 
* Event streaming applications should be the recently added [Kinesis streaming functionality](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/kds.html) top capture event streaming changes from Dynamodb, which would use the more robust `fs2-aws-kinesis` module
* Those applications which use native dynamodb streaming (e.g. lambda consumers) should look at the [aws-lambda-java-events-sdk-transformer](https://github.com/aws/aws-lambda-java-libs/tree/main/aws-lambda-java-events-sdk-transformer) for code which converts the payload.

**Comment by semenodm** [comment]
i prefer something like option 1.
use `com.amazonaws.services.dynamodbv2.model.AttributeValue` as the output of the stream and let the user choose how to parse this.

**Comment by kovszilard** [comment]
What about removing the streaming support and adding support for parsing dynamo events to the fs2-aws-kinesis module. We have implemented this functionality at work, it uses magnolia for automatic typeclass derivation. If you like this solution, I think I can contribute to this project.

**Comment by semenodm** [comment]
@barryoneill I removed scnamo from the ddb streaming. Can we close this one?

**Comment by barryoneill** [comment]
Nice one @semenodm - closing!
