### ISSUE TITLE
Release Action failing

### ISSUE THREAD

**Issue by tmilner** [laserdisc-io/fs2-aws#1217]
This maybe a known issue, but I noticed that the release action has failed for the last few weeks - https://github.com/laserdisc-io/fs2-aws/actions/workflows/release.yml

**Comment by semenodm** [comment]
i think it is related to [this](https://github.com/profunktor/http4s-jwt-auth/issues/453) issue that has been resolved with some snapshot versions of the ci-release and sonotype sbt plugins 
I will try to follow the steps and fix it

**Comment by semenodm** [comment]
ok, generating access token and updating secrets in GH was enough. [release action](https://github.com/laserdisc-io/fs2-aws/actions/runs/9929295314/job/27627936107) is green now
