### ISSUE TITLE
Kinesis: make CommitableRecord.checkpoint() referentially-transparent

### ISSUE THREAD

**Issue by chuwy** [laserdisc-io/fs2-aws#203]
[`checkpoint()`](https://github.com/laserdisc-io/fs2-aws/blob/1dc818a7308505fc4d3d92025cd57044665799b1/fs2-aws/src/main/scala/fs2/aws/kinesis/CommittableRecord.scala#L27-L28) has `Unit` return type, while it's clearly side-effectful (as well as `canCheckpoint`). Wondering if there are technical reasons for not having `F[_]: Sync`?

**Comment by semenodm** [comment]
No there is no tech reason to keep it this way. CommitableRecord (holding vars of chkpointer and record processor) class and the way we do checkpointing is not good and has to be rethink.
