### ISSUE TITLE
Publish fs2-aws-sqs for 3.x

### ISSUE THREAD

**Issue by chuwy** [laserdisc-io/fs2-aws#539]
I might be missing something, but when I add `fs2-aws:3.0.2` as a dependency I don't have `fs2.aws.sqs` package.

Also don't see AWS SQS runtime dependency [on Maven](https://mvnrepository.com/artifact/io.laserdisc/fs2-aws_2.13/3.0.3-MODA1), though 2.29.0 works as expected.

**Comment by semenodm** [comment]
@chuwy it is embarrassing , but it seams we forgot to include it into the to the root project and it is not part of the release process

**Comment by semenodm** [comment]
@chuwy can you try `3.0.6` https://github.com/laserdisc-io/fs2-aws/actions/runs/414084461
