### ISSUE TITLE
Kinesis consumer returns `StreamName should not be empty`

### ISSUE THREAD

**Issue by gregorath** [laserdisc-io/fs2-aws#605]
**Problem**
-----------
After upgrading to `v3.0.9` using `readFromKinesisStream`  with the default `FanOut` retrieval mode returns the following error. The `streamName` in `KinesisConsumerSettings` is set properly.

```
[info] ERROR 2021-03-01 15:09:49,630 s.a.kinesis.coordinator.Scheduler - Worker.run caught exception, sleeping for 1000 milli seconds!
[info] java.lang.NullPointerException: StreamName should not be empty
[info] 	at software.amazon.awssdk.utils.Validate.notEmpty(Validate.java:290)
[info] 	at software.amazon.kinesis.common.StreamIdentifier.singleStreamInstance(StreamIdentifier.java:85)
[info] 	at software.amazon.kinesis.retrieval.fanout.FanOutRetrievalFactory.createGetRecordsCache(FanOutRetrievalFactory.java:63)
[info] 	at software.amazon.kinesis.coordinator.Scheduler.buildConsumer(Scheduler.java:915)
[info] 	at software.amazon.kinesis.coordinator.Scheduler.createOrGetShardConsumer(Scheduler.java:890)
[info] 	at software.amazon.kinesis.coordinator.Scheduler.runProcessLoop(Scheduler.java:416)
[info] 	at software.amazon.kinesis.coordinator.Scheduler.run(Scheduler.java:325)
[info] 	at fs2.aws.kinesis.consumer$.$anonfun$readChunksFromKinesisStream$7(consumer.scala:239)
```

The application tries to read from one stream which has one shard.
Switching to `Polling` works fine.

**Comment by semenodm** [comment]
Hi. I'm sorry for this bug, we introduced it when we adopted the integration with LocalStack
Please try version 3.0.11 i just released with fix
Also consider using https://github.com/laserdisc-io/fs2-aws/blob/master/fs2-aws/src/main/scala/fs2/aws/kinesis/Kinesis.scala
the usage example https://github.com/laserdisc-io/fs2-aws/blob/master/fs2-aws-examples/src/main/scala/KinesisExample.scala

I'm planning to open the Discussion to compare these 2 APIs and choose one of them at the end

**Comment by semenodm** [comment]
i would love encourage you to participate in this discussion https://github.com/laserdisc-io/fs2-aws/discussions/607

**Comment by gregorath** [comment]
Thank you for fixing this so quickly. I will upgrade and try the new implementation as well.
