### ISSUE TITLE
Type mismatch when upgrading from 3.0.7 to 3.0.9

### ISSUE THREAD

**Issue by gbastkowski** [laserdisc-io/fs2-aws#637]
Having an S3 client up and running, basically as described in the readme, an upgrade from 3.0.7 to version 3.0.9 leads to the following compile error:

```
[error]  found   : software.amazon.awssdk.services.s3.S3Client
[error]  required: io.laserdisc.pure.s3.tagless.S3AsyncClientOp[?]
[error]         .eval(S3.create(awsS3SyncClient, blocker))
```

**Comment by semenodm** [comment]
I will fix the readme

**Comment by semenodm** [comment]
@gbastkowski please check the latest changes in readme plus S3 examples

**Comment by ettenger** [comment]
@semenodm Thanks for updating the readme! It works for me after making this change: `S3Interpreter` should be `Interpreter`

**Comment by semenodm** [comment]
https://github.com/laserdisc-io/fs2-aws/blob/main/fs2-aws-examples/src/main/scala/fs2/aws/examples/S3Example.scala#L6
