### ISSUE TITLE
v4.0.0-RC1 Availability

### ISSUE THREAD

**Issue by natevecc** [laserdisc-io/fs2-aws#696]
Thanks for running this project. Interested to try it out with CE3 and was wondering if v4.0.0-RC1 was available prebuilt anywhere? I didn't see it on maven.

**Comment by semenodm** [comment]
hello can you give me more details, because i can see it was published to sonatype

**Comment by semenodm** [comment]
https://mvnrepository.com/artifact/io.laserdisc/fs2-aws-kinesis_2.13/4.0.0-RC1

**Comment by natevecc** [comment]
Oh I was looking at the wrong spot 🤦 https://search.maven.org/artifact/io.laserdisc/fs2-aws_2.13. Ignore me.
