### ISSUE TITLE
should S3 create method require Concurrent?

### ISSUE THREAD

**Issue by wim82** [laserdisc-io/fs2-aws#707]
hello,
i was playing with Doobie and streaming to S3 and had some problems of making it work cause i would like to work within the doobie effect `ConnectionIO` which does not implement `Concurrent` while the `create` method of `fs2.aws.s3.S3` does require it.

I dont see why (yet?)

```scala
    def create[F[_]: Async: Concurrent](s3: S3AsyncClientOp[F]): F[S3[F]] 
```

would the following be sufficient (at least it compiles)?

```scala
    def create[F[_]: Async](s3: S3AsyncClientOp[F]): F[S3[F]] 
```

**Comment by semenodm** [comment]
Does ConnectionIO gives you Async?
Also you might be right and we can remove this dependency

**Comment by wim82** [comment]
Yes, it does: https://github.com/tpolecat/doobie/blob/e9584dfcdd2b971a3e7c05a448bbe027b29097be/modules/core/src/main/scala/doobie/free/Aliases.scala#L55

But i think it no longer does in the new version which uses Cats Effect 3 under the hood. 

After learning a bit more about this, i came to realise this is probably not the right path for me (in the end i try to upload a file within a db transaction, which maybe is not the smartest idea). 

So, the issue can be closed as i don't think it matters that much for most users, and soon things will change anyway?

**Comment by semenodm** [comment]
but i think you are right and i should remove Concurrent from the required type classes
