### ISSUE TITLE
Pipe method signature prevents changing the Stream effect type

### ISSUE THREAD

**Issue by jarrodcodes** [laserdisc-io/fs2-aws#734]
Hello! I have a requirement to use fs2-aws-s3 within a tracing context. We are using [trace4cats](https://github.com/trace4cats) and thus our effect type is `Kleisli[F, Span[F], *`. For most of our use cases, changing to this effect type has been either built in or easy to add. For fs2, we have the option of using the [translate](https://github.com/typelevel/fs2/blob/c0178587cb4d978ae47ee25bab12ca8b2a36cc66/core/shared/src/main/scala/fs2/Stream.scala#L2580) method. However, because the public API for fs2-aws-s3 has a method signature of `Pipe[F, Byte, ETag]` for the methods of `uploadFile` and `uploadFileMultipart`, we cannot apply the `translate` method and thus cannot easily change the effect type.

A few options would be:

1. add similar methods that return a Stream
2. add a new s3 object called s3Streams (or similar) with these methods using shared logic
3. Add an effect translation method, (i.e. mapK)

With any of these options a new effect type can easily be applied for all methods.
Happy to make a PR with whichever option is decided by the maintainers. Thanks for your time.

**Comment by semenodm** [comment]
Hey, sorry for late response.
What option are you personally inclined to? i like option 3

**Comment by jarrodcodes** [comment]
I agree with #3, and made a PR: [#737.](https://github.com/laserdisc-io/fs2-aws/pull/737).

**Comment by semenodm** [comment]
@jarrodcodes thanks again for the contribution, should we close the issue now?

**Comment by jarrodcodes** [comment]
Yes, thank you!
