### ISSUE TITLE
Readme.MD examples do not compile

### ISSUE THREAD

**Issue by SimunKaracic** [laserdisc-io/fs2-aws#772]
From `README.md`:
```
Stream.emits("test data".getBytes("UTF-8"))
  .through(s3.uploadFileMultipart(BucketName("foo"), FileKey("bar"), partSize = 5))
  .evalMap(t => IO(println(s"eTag: $t")))
```

Does not work anymore, since 5 is an `Int`, and not a `PartSizeMB`.
Any pointers on how to create an instance of `PartSizeMB`?

Update:
Fixed by copying the definition of `PartSizeMB` to my codebase, but I'd rather not import it if there's a better way

**Comment by semenodm** [comment]
hello, thanks for using this library
the defintion can be found here https://github.com/laserdisc-io/fs2-aws/blob/d4e51f82cca7a1f61af17021ccdadb57851183cf/fs2-aws-s3/src/main/scala/fs2/aws/s3.scala#L24
you just need to import it, not copy

**Comment by SimunKaracic** [comment]
Thanks for the help!
