### ISSUE TITLE
s3.listFiles does not manage truncation

### ISSUE THREAD

**Issue by shn-amn** [laserdisc-io/fs2-aws#81]
In response to a ListObjectsV2Request, if a bucket contains too many objects (more than a 1000 in my experience), AWS automatically truncates the response to a reasonable size (1000, as before) and sends along with it a continuation token to send the next request. 

This behaviour is completely ignored by s3.listFiles, leading to an obvious bug while listing crowded buckets.

**Comment by kiambogo** [comment]
Looks like auto-pagination is supported in v2 of the SDK, so I think its best to focus on migrating the S3 functions to V2 of the SDK instead of adding in support for manual pagination. 

https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/examples-pagination.html

**Comment by semenodm** [comment]
i think we lost this algebra when migrated to V2 other day, pleas confirm @shn-amn
