### ISSUE TITLE
Unused values in `KinesisSettings`

### ISSUE THREAD

**Issue by mrdziuban** [laserdisc-io/fs2-aws#812]
The `maxConcurrency`, `stsAssumeRole`, and `endpoint` values in `KinesisSettings` are not used anywhere else in the code. It looks like when they were added they were each used for building a `KinesisAsyncClient` in `consumer.scala`:

- [`maxConcurrency`](https://github.com/laserdisc-io/fs2-aws/commit/c30f1a5c822fec17bc9f9a73d33df15ac35b4570#diff-a9cad65a80804926290d8784057b2e70eec2c0e9afbc35e5d87fb00b15e867c8R30)
- [`stsAssumeRole`](https://github.com/laserdisc-io/fs2-aws/commit/7a0a77fcc42edfddd6e17266b7abe634b4430770#diff-a9cad65a80804926290d8784057b2e70eec2c0e9afbc35e5d87fb00b15e867c8R30)
- [`endpoint`](https://github.com/laserdisc-io/fs2-aws/commit/c33c249a1cddfca688e5af4ef7a0e0e7a1ba39c3#diff-a9cad65a80804926290d8784057b2e70eec2c0e9afbc35e5d87fb00b15e867c8R29)

However it looks like [`consumer.scala` was removed as part of the cats-effect 3 upgrade](https://github.com/laserdisc-io/fs2-aws/commit/beedb45532dd8f593a667fb45690b06e599bc6ee#diff-a9cad65a80804926290d8784057b2e70eec2c0e9afbc35e5d87fb00b15e867c8). Would it make sense to remove these values as well? Or would it make more sense to restore some functionality to build a kinesis client given some `KinesisSettings`?

**Comment by semenodm** [comment]
thanks for reporting the issue. i will address it asap
