### ISSUE TITLE
Artifact not resolving (5.x & 4.x)

### ISSUE THREAD

**Issue by TobiasRoland** [laserdisc-io/fs2-aws#842]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/5878818/160576673-726738c4-10ba-47c8-b9c3-57bc751618e7.png">

Hi there! 👋 

I am unable to follow these instructions and get the latest verison, the snippet with 5.0.0 fails to resolve.

Looking at https://repo1.maven.org/maven2/io/laserdisc/ it doesn't look like there is a `fs2-aws` artifact - does the docs need to be updated, or is there an artifact that doesn't get published as expected?

**Comment by semenodm** [comment]
indeed, i need to update docs. in fact this is my next priority.
to address your issue, you need to add dependency specific to your aws service 
for example, if you use SQS module you need to add 

```scala
libraryDependencies +=  "io.laserdisc" %% "fs2-aws-sqs" % "VERSION"
```
we modularized the project into different components by aws resources
