### ISSUE TITLE
SQS default fetch message count is greater than max allowed

### ISSUE THREAD

**Issue by SimY4** [laserdisc-io/fs2-aws#847]
SQS seem to support fetch message count between 1 and 10. The library's default is 100.

**Comment by semenodm** [comment]
thanks for finding this, i think we need to use refined types in this case to nail it to allowed range

**Comment by SimY4** [comment]
@semenodm IMO it’s better to keep the value open to keep the code agnostic to any AWS changes. But changing the default is still worth doing
