### ISSUE TITLE
Need to support non-default CredentialProvider when building KinesisAsyncClient 

### ISSUE THREAD

**Issue by farhan-narrativeio** [laserdisc-io/fs2-aws#90]
For apps that need to use assume-role or session credentials (see https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenJava.html), the current approach does not work.  Some possible solutions:
1) Make add an optional CredentialsProvider field to fs2.aws.kinesis.KinesisConsumerSettings, and use that in fs2.aws.kinesis.defaultScheduler() when building KinesisAsyncClient.

or 2) Make  fs2.aws.kinesis.defaultScheduler() public or protected

or 3) Make fs2.aws.kinesis.readFromKinesisStream() public or protected

**Comment by semenodm** [comment]
all AWS clients are now configured externally
