### ISSUE TITLE
S3.create returns `F[S3[F]]` when it could just be pure?

### ISSUE THREAD

**Issue by hejfelix** [laserdisc-io/fs2-aws#937]
https://github.com/laserdisc-io/fs2-aws/blob/9ec10e57c36b9cdb31c4eb199f26ac92188d2038/fs2-aws-s3/src/main/scala/fs2/aws/s3/S3.scala#L43

It looks to me like this should just return `S3[F]`, is there a reason behind this?

**Comment by semenodm** [comment]
You are right, there is no need to wrap it into effect
