### ISSUE TITLE
Dynamodb StreamScan hangs forever if a client error happens

### ISSUE THREAD

**Issue by gianlo** [laserdisc-io/fs2-aws#986]
The code produces a stream from a None terminated queue.
However in the onError method of the subscriber, the exception thrown by the dynamo client is [raised](https://github.com/laserdisc-io/fs2-aws/blob/d185ec97e0c639bd45fbf5d2ea57cb39d2270347/fs2-aws-dynamodb/src/main/scala/fs2/aws/dynamodb/StreamScan.scala#L66), but a None is not published to the underlying Queue and therefore the stream never terminates.

**Comment by semenodm** [comment]
The intent was to raise the error and shut down the app. it looks like this is not what happens.

**Comment by gianlo** [comment]
This can potentially be tested by injecting a dynamodb client that fails predictably (e.g. setting up the connection acquisition timeout of the underlying httpclient to 1 nano).
